// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Initialize():Promise<string>;

export function Listen(arg1:boolean,arg2:string):Promise<string>;

export function LoadDevices():Promise<string>;
