// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Initialize() {
  return window['go']['main']['App']['Initialize']();
}

export function Listen(arg1, arg2) {
  return window['go']['main']['App']['Listen'](arg1, arg2);
}

export function LoadDevices() {
  return window['go']['main']['App']['LoadDevices']();
}
